### ISSUE TITLE
Make boulder pass $HOME to moss-container by default

### ISSUE THREAD

**Issue by ermo** [serpent-os/boulder#10]
This is needed for a couple of builds, so might as well follow the principle of least surprise and set it always.

`"-s", format!"HOME=\"%s\""(context.job.guestPaths.buildRoot),` was Ikey's suggestion (capturing for reference)

**Comment by ermo** [comment]
ping @ReillyBrogan

**Comment by ReillyBrogan** [comment]
Works fine now, thanks!
