### ISSUE TITLE
Generate index automatically

### ISSUE THREAD

**Issue by ReillyBrogan** [serpent-os/boulder#11]
QOL feature, it shouldn't be necessary to run `moss idx` after modifying the contents of a collection folder. Boulder should do it automatically when it detects that the contents have changed.

**Comment by sunnyflunk** [comment]
There should be a flag for `boulder` where you do a build, it copies the resulting stones to the local repo dir from the profile and then reindexes. That is essentially what a user wants when creating an overlay
