### ISSUE TITLE
%reconfigure should install autoconf

### ISSUE THREAD

**Issue by ReillyBrogan** [serpent-os/boulder#18]
Title. If a recipe uses the %reconfigure macro it should automatically add the autoconf package as a builddep.

**Comment by joebonrichie** [comment]
Looks like it already does? https://github.com/serpent-os/boulder/blob/main/data/macros/actions/autotools.yml#L30

Possibly because your boulder stone is not fully up to date.

**Comment by ReillyBrogan** [comment]
Yeah I think I didn't realize this one was fixed too (I opened #17 before realizing it was already fixed)
