### ISSUE TITLE
Option to disable stripping

### ISSUE THREAD

**Issue by ReillyBrogan** [serpent-os/boulder#21]
~~SerpentOS is not a clothing-optional distro like OtherOS~~ Some packages like golang (and _maybe_ just golang) do funky things to their binaries that break when you try to strip them. Add a toggle to prevent this stripping from happening.

**Comment by joebonrichie** [comment]
moss-format has a strip option but i guess it's not hooked up properly?

**Comment by joebonrichie** [comment]
Commented out atm: https://github.com/serpent-os/boulder/blob/main/source/mason/build/builder.d#L255
