### ISSUE TITLE
boulder should catch sigint (Ctrl+C) and cleanup after itself

### ISSUE THREAD

**Issue by joebonrichie** [serpent-os/boulder#22]
After receiving a sigint signal boulder should catch it and cleanly umount any directories plus perform any other cleanup as needed to prevent manual intervention to get boulder going again upon a new build.

There is code already attempting to resolve this but doesn't seem to work properly:
https://github.com/serpent-os/boulder/blob/main/source/boulder/controller.d#L270

**Comment by sunnyflunk** [comment]
It used to be clean, but the addition of the pkgCache leaves that directory mounted only.

Need to trace down what the mountPoints actually are. The addMount should be added here to make it a mountPoint to later unmount https://github.com/serpent-os/boulder/blob/c63b7b20d23f09bc867f8b900fcec1960a4b3c4c/source/boulder/stages/create_root.d#L67

**Comment by sunnyflunk** [comment]
So looking into this:

```
##### Mount Points: [Mount("/var/cache/boulder/pkgCache", "/var/cache/boulder/root/nano-5.5-2/.moss/cache", "", Bind, None)]
```

Are stored as mount points to be unmounted on exit here: https://github.com/serpent-os/boulder/blob/main/source/boulder/controller.d#L270 but this only runs if `boulder` either errors or finishes. If you Ctrl+C, this does not run and why it remains mounted. The rest of the mounts exit cause `moss-container` handles them and umounts on the Ctrl+C

I'm not sure when/where "/var/cache/boulder/pkgCache" gets mounted (maybe cause I have all the files fetched already), but it also gets unmounted in that case at some point

**Comment by sunnyflunk** [comment]
So this runs on Ctrl+C https://github.com/serpent-os/moss-container/blob/main/source/moss/container/package.d#L84, but doesn't signal (or fall through) to `boulder` to do it's `scope (exit)`
