### ISSUE TITLE
json manifest should show what a package provides

### ISSUE THREAD

**Issue by ReillyBrogan** [serpent-os/boulder#23]
Currently the only way to see what a recipe directly provides (like soname(whatever) ) is to build that package and check the output at the end of the build. It would be nice and user friendly if the manifest stored this information so that we could see a package that we didn't build ourselves and know the various methods we can depend on it in other recipes. 

It would also be helpful to catch possibly unintended changes and during package review cycles.

**Comment by sunnyflunk** [comment]
It also needs to include dependencies in the manifest. And the ABI data is still missing but not necessarily in the manifest file.
