### ISSUE TITLE
`paths` do not expand macros as expected

### ISSUE THREAD

**Issue by joebonrichie** [serpent-os/boulder#29]
For example
```
paths  : |
    - libs :
        - %(libdir)%/libfoo*.so*
```

You would expect `%(libdir)%` to expand to `/usr/lib` but it currently doesn't.

**Comment by sunnyflunk** [comment]
I feel like this got fixed, but requires a new boulder to be built into the repo packages (also note the extra % in your example, it's just `%(libdir)`)

**Comment by livingsilver94** [comment]
Duplicate of serpent-os/moss-format/issues/2

**Comment by joebonrichie** [comment]
Duplicate
