### ISSUE TITLE
Some `man` sections should be detected as part of a `-devel` subpackage

### ISSUE THREAD

**Issue by livingsilver94** [serpent-os/boulder#47]
Here is an excerpt of `man man`:

       1   Executable programs or shell commands
       2   System calls (functions provided by the kernel) 
       3   Library calls (functions within program libraries)
       4   Special files (usually found in /dev)
       5   File formats and conventions, e.g. /etc/passwd
       6   Games
       7   Miscellaneous (including macro packages and conventions), e.g. man(7), groff(7), man-pages(7)
       8   System administration commands (usually only for root)
       9   Kernel routines [Non standard]

I think sections 2, 3 and 9 should be automatically added in `-devel` subpackages. What do you think?

**Comment by joebonrichie** [comment]
Makes sense to me. Should be easy enough to add the rules to: https://github.com/serpent-os/boulder/blob/main/data/macros/arch/base.yml#L497
