### ISSUE TITLE
Git sources require networking: yes

### ISSUE THREAD

**Issue by ReillyBrogan** [serpent-os/boulder#55]
Tried the git support with glibc and got the following error message:
```
+ git -C glibc init
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint:   git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint:   git branch -m <name>
Initialized empty Git repository in /mason/build/build/emul32/x86_64/glibc/.git/
+ git -C glibc remote add origin https://sourceware.org/git/glibc.git
+ git -C glibc fetch --depth 1 origin d8e1a7590d375159fb5aac07ad8111ab4699e994
fatal: unable to access 'https://sourceware.org/git/glibc.git/': Could not resolve host: sourceware.org
+ echo Failed to fetch git repo
Failed to fetch git repo
```

This went away when I added `networking: yes`. The git steps should probably be ran on the host instead of from within the build environment to prevent unnecessary network access, or having a git source URI should imply `networking: yes`.

**Comment by GZGavinZhao** [comment]
Huh, I thought I made the fetching step to run on the host, and if I didn't, I should've gotten the same error when I was testing. I'll have to check that. Are you using `glibc` recipe file in snekpit/toolchain#5?

**Comment by ReillyBrogan** [comment]
> Huh, I thought I made the fetching step to run on the host, and if I didn't, I should've gotten the same error when I was testing. I'll have to check that. Are you using `glibc` recipe file in [snekpit/toolchain#5](https://github.com/snekpit/toolchain/pull/5)?

Yes.

**Comment by GZGavinZhao** [comment]
The commands look like those at [here](https://github.com/serpent-os/boulder/pull/50/files#diff-790a25daab36c6ea341acea39b87dfe4f205e14d9b8ac658abb23a8bea030171) which I clearly deleted in the Git PR. Though the question may seem double, are you using the latest version?

**Comment by ReillyBrogan** [comment]
OK, I tested again just now and I think the issue was that boulder in the repos was outdated (updated by Ikey in [commit](https://github.com/snekpit/main/commit/1b99085a27810752db418a9d9bcf39f0aa4fa653). This is resolved now.
