### ISSUE TITLE
UX: Running confined builds (the default) requires root. Tell the user this up front.

### ISSUE THREAD

**Issue by ermo** [serpent-os/boulder#9]
This better follows the principle of least surprise. No point in failing with an exception due to missing access rights later.

**Comment by livingsilver94** [comment]
I think the medium term plan is to manage exception and avoid showing them altogether, as exceptions look threatening.

**Comment by ermo** [comment]
Fixed with https://github.com/serpent-os/boulder/commit/4bd6b6be7bce1cb3c543be0a94d5fabea3dc7d50
